- name: Install NFS packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - nfs-kernel-server
    - nfs-common

- name: Create shared directory
  file:
    path: /mnt/nfs_share
    state: directory
    owner: nobody
    group: nogroup
    mode: '0777'

- name: Format disk 
  filesystem:
    fstype: ext4
    dev: /dev/disk/by-id/google-nfs-disk

- name: Mount NFS disk
  mount:
    path: /mnt/nfs_share
    src: /dev/disk/by-id/google-nfs-disk
    fstype: ext4
    state: mounted

- name: Configure exports
  copy:
    dest: /etc/exports
    content: |
      /mnt/nfs_share *(rw,sync,no_subtree_check,no_root_squash)

- name: Export NFS shares
  command: exportfs -ra

- name: start NFS service
  service:
    name: nfs-kernel-server
    state: started
    enabled: yes

