- name: Download Kafka
  get_url:
    url: https://downloads.apache.org/kafka/3.9.0/kafka_2.13-3.9.0.tgz
    dest: /opt/kafka.tgz

- name: Extract Kafka
  unarchive:
    src: /opt/kafka.tgz
    dest: /opt/
    remote_src: yes

- name: Create symlink to Kafka
  file:
    src: /opt/kafka_2.13-3.9.0
    dest: /opt/kafka
    state: link

- name: Ensure Kafka log directory exists
  file:
    path: /tmp/kafka-logs
    state: directory
    mode: '0755'

- name: Copy Kafka configuration from template
  template:
    src: server.properties.j2
    dest: /opt/kafka/config/server.properties

- name: Create Kafka systemd service
  copy:
    dest: /etc/systemd/system/kafka.service
    content: |
      [Unit]
      Description=Apache Kafka Server
      After=network.target

      [Service]
      Type=simple
      ExecStart=/opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
      ExecStop=/opt/kafka/bin/kafka-server-stop.sh
      Restart=on-abnormal

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start Kafka
  systemd:
    name: kafka
    enabled: yes
    state: started
