- name: Install NFS client
  apt:
    name: nfs-common
    state: present
    update_cache: yes

- name: Create mount point
  file:
    path: /mnt/nfs
    state: directory

- name: Mount NFS share
  mount:
    path: /mnt/nfs
    src: "{{ nfs_server_ip }}:/mnt/nfs_share"
    fstype: nfs
    opts: defaults
    state: mounted



- name: Create user spark
  user:
    name: spark
    shell: /bin/bash
    create_home: yes

- name: Download Spark
  get_url:
    url: https://dlcdn.apache.org/spark/spark-3.5.6/spark-3.5.6-bin-hadoop3.tgz
    dest: /opt/spark.tgz

- name: Extract Spark
  unarchive:
    src: /opt/spark.tgz
    dest: /opt/
    remote_src: yes

- name: Create symlink
  file:
    src: /opt/spark-3.5.6-bin-hadoop3
    dest: /opt/spark
    state: link
