- hosts: all
  become: true
  roles:
    - base

- hosts: driver:spark_master:spark_workers
  become: true
  roles:
    - spark-common

- hosts: driver
  become: true
  roles:
    - driver

- hosts: zookeeper
  become: true
  roles:
    - zookeeper

- hosts: kafka
  become: true
  roles:
    - kafka

- hosts: spark_master
  become: true
  roles:
    - spark-master

- hosts: spark_workers
  become: true
  roles:
    - spark-worker

